import Head from "next/head";
import BottomFooter from "../components/footer/BottomFooter";
import UpperFooter from "../components/footer/UpperFooter";
import MenuHeader from "../components/header/menuHeader";
import TopHeader from "../components/header/topHeader";
import SignInCTA from "../components/SignInCTA";
import styles from "../styles/Home.module.scss";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        {/* <link rel="icon" href="/favicon.ico" /> */}
      </Head>

      <TopHeader />
      <MenuHeader />
      {/* <MegaMenu/> */}
      <SignInCTA />
      <UpperFooter />
      <BottomFooter />
    </div>
  );
}
