import Head from 'next/head'
import Image from 'next/image'
import BottomFooter from '../components/footer/bottomFooter'
import UpperFooter from '../components/footer/UpperFooter'
import MegaMenu from '../components/header/MegaMenu'
import MenuHeader from '../components/header/menuHeader'
import TopHeader from '../components/header/topHeader'
import SignInCTA from '../components/SignInCTA'
import styles from '../styles/Home.module.scss'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    <TopHeader/>
    <MenuHeader/>
    {/* <MegaMenu/> */}
    <SignInCTA/>
    <UpperFooter/>
    <BottomFooter/>
    </div>
  )
}
